### ISSUE TITLE
FileNotFoundError after updating siegfried 

### ISSUE THREAD

**Issue by ShellyYBlack** [tw4l/brunnhilde#59]
After updating siegfried from 1.9.6 to 1.10.0, I'm getting this output when running brunnhilde. 
```
Traceback (most recent call last):
  File "/usr/local/bin/brunnhilde.py", line 1385, in <module>
    main()
  File "/usr/local/bin/brunnhilde.py", line 1253, in main
    siegfried_version = subprocess.check_output(["sf", "-version"]).decode()
  File "/usr/lib64/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sf'
```
I've tested this on Mac Monterey and Linux Fedora 36. Thank you for your help.

**Comment by tw4l** [comment]
Thanks @ShellyYBlack ! If you run `sf` manually in your terminal, does it work? It may need to be added to your PATH

**Comment by ShellyYBlack** [comment]
@tw4l sf by itself has been working. Also, sorry, I hadn't updated PATH. I just did that on Fedora now, then ran brunnhilde again. Now I get this:
```
Traceback (most recent call last):
  File "/usr/local/bin/brunnhilde.py", line 1385, in <module>
    main()
  File "/usr/local/bin/brunnhilde.py", line 1359, in main
    process_content(
  File "/usr/local/bin/brunnhilde.py", line 947, in process_content
    use_hash = import_csv(cursor, conn, use_hash)
  File "/usr/local/bin/brunnhilde.py", line 312, in import_csv
    cursor.execute(insertsql, row)
sqlite3.OperationalError: table siegfried has 11 columns but 13 values were supplied
```

@kieranjol I think `sf -v` previously didn't show me the version number but now it does.

**Comment by tw4l** [comment]
Thanks @ShellyYBlack ! I'm going to close this issue in favor of https://github.com/tw4l/brunnhilde/issues/60 since it's a bit more descriptive of the error you're seeing now that sf is available via `PATH`. Will work on a fix this week and give updates there!
